export const credentials = [
 ["AWS Solutions Architect", "Associate", "6c264a94-0bc4-40f2-9a59-dd1d631c5ee5"],
 ["AWS Machine Learning", "Associate", "7361e806-e34c-458f-824d-73152035b1ae"],
 ["AWS AI Practitioner", "AIF-C01", "ae72c38d-7367-49e2-a50d-cff5d97b9818"],
 ["AWS Generative AI", "Practice test badge", "5457263a-cc6c-448a-b29e-1e942ebf8a58"],
 ["Amazon Connect", "Implementation training", "689205de-f003-4924-b814-a4183daab353"],
 ["Lean Six Sigma", "Green Belt · certificate on request", ""],
 ["Data Visualization with Python", "Certificate", ""],
 ["Data Visualisation", "Forage job simulation", ""]
];
export const resources = [
 ["Contact flow templates", "IVR · Queues · Callbacks"],
 ["Lex self-service starter", "Intents · Fulfillment · Fallbacks"],
 ["Salesforce SCV integration", "Screen-pop · OAuth · Webhooks"],
 ["Migration runbook", "Flow mapping · Validation · Hypercare"],
 ["Monitoring toolkit", "CloudWatch · Splunk · Contact Lens"],
 ["Infrastructure templates", "CloudFormation · Terraform"],
 ["Cloud5ence source", "Website · Infrastructure · Deployment"]
];
export const notes = ["The details that make an IVR feel effortless", "What to map before a CCaaS migration", "When a screen-pop arrives too late", "Designing a useful Lex fallback", "Listening better with Contact Lens", "Building a cloud delivery pipeline", "Building contact flows for regulated environments"];


export const services = [
 {id:"strategy",title:"CX Strategy & Advisory",short:"Strategy",headline:"A clear direction for your next customer experience.",summary:"We turn fragmented journeys, legacy constraints, and competing priorities into a practical CX roadmap. Start with the business problem, assess the current environment, and make technology decisions with a clear delivery plan.",scope:["Customer journey and contact center assessment","Platform fit, architecture, and integration planning","Prioritized roadmap and implementation scope"],fit:"You need to decide what to modernize, which platform fits, or where to invest first.",outcome:"An agreed direction, a realistic sequence of work, and a clear definition of success."},
 {id:"implementation",title:"CCaaS Implementations",short:"Implement",headline:"Modern contact centers. Thoughtful transitions.",summary:"We design and implement cloud contact centers with Amazon Connect and Genesys Cloud CX. From IVR and routing to integrations and cutover planning, we keep the customer journey at the center of the implementation.",scope:["Contact flows, queues, routing, and callbacks","Platform migration and CRM integration","Journey testing, cutover planning, and handover"],fit:"You are moving to the cloud, replacing a platform, or rebuilding customer journeys.",outcome:"A contact center implementation with connected workflows and a defined launch and validation plan."},
 {id:"managed",title:"CCaaS Managed Services",short:"Optimize",headline:"Keep the experience working. Keep making it better.",summary:"We help teams maintain and improve their contact center environment after launch. Monitoring, configuration reviews, incident investigation, and controlled changes keep operational needs connected to the customer experience.",scope:["Platform administration and configuration support","Monitoring, alerting, and incident investigation","Routing improvements and release coordination"],fit:"You need specialist support for ongoing operations and continuous improvement.",outcome:"An agreed support scope, clearer operational visibility, and a prioritized improvement backlog."},
 {id:"integrations",title:"Custom Integrations",short:"Connect",headline:"The right information, where the conversation happens.",summary:"We connect contact center platforms with CRM, business applications, and cloud services. APIs and serverless workflows carry context between systems and reduce repetitive work for the people using them.",scope:["AWS Lambda, API Gateway, and backend APIs","CRM screen-pop and customer context lookup","Workflow automation and integration monitoring"],fit:"Customer information is scattered or agents repeat work across disconnected systems.",outcome:"Connected workflows that move useful context between applications and the contact center."},
 {id:"ai",title:"AI for CX & Contact Centers",short:"Automate",headline:"Useful self-service. A thoughtful path to a person.",summary:"We design voice and chat automation around real customer needs. Conversational AI, intent fulfillment, and speech analytics help resolve routine requests while keeping fallbacks and agent handoffs part of the design.",scope:["Amazon Lex voice and chat self-service","Lambda fulfillment, fallback, and escalation paths","Contact Lens analytics and journey optimization"],fit:"You want to automate recurring enquiries without creating another frustrating customer journey.",outcome:"Defined self-service intents, connected fulfillment, and tested paths for errors and human support."},
 {id:"salesforce",title:"Salesforce for CX",short:"Unify",headline:"One conversation. A more complete customer view.",summary:"We bring contact center interactions into the CRM workspace with Salesforce Service Cloud Voice and connected APIs. Screen-pop, interaction logging, and case workflows give agents more context with less manual effort.",scope:["Contact center and Salesforce SCV integration","Customer screen-pop and interaction logging","Case creation and post-contact automation"],fit:"Agents need customer context and follow-up workflows in the tools they already use.",outcome:"A connected agent experience that carries the conversation into service and follow-up workflows."},
 {id:"salesforce-support",title:"Salesforce Managed Services",short:"Support",headline:"Keep your connected service workflows moving.",summary:"We support the Salesforce workflows and integrations behind your customer experience. Our focus is on the contact center connection: diagnosing integration issues, refining automation, and validating changes as business needs evolve.",scope:["CX integration troubleshooting and maintenance","Service workflow and automation refinement","Release validation and operational documentation"],fit:"Your Salesforce-connected contact center needs ongoing integration and workflow support.",outcome:"A defined maintenance and improvement plan for the Salesforce components in your CX environment."}
];

export const solutions = [
 {id:"routing",sector:"Banking",title:"Intelligent customer routing",summary:"Helping banking customers reach the right team with fewer unnecessary transfers.",metric:"25%",metricLabel:"fewer misrouted transfers",stack:["Amazon Connect","AWS Lambda","Contact Lens","Splunk"],challenge:"The client needed more accurate contact routing and faster access to customer information during banking support calls.",solution:"We designed dynamic Amazon Connect journeys with Lambda-based customer lookup and contact-attribute routing. Contact Lens analytics and Splunk alerting provided operational visibility.",delivery:["Dynamic IVR and customer segmentation","Backend lookup and routing integration","Journey analytics and operational alerts"],result:"Approximately 25% fewer misrouted transfers. Agent screen loading was reduced from 45 seconds to under 8 seconds."},
 {id:"agent-workspace",sector:"Banking",title:"A connected agent workspace",summary:"Bringing voice, customer records, and follow-up into a connected service workflow.",metric:"35%",metricLabel:"higher agent productivity",stack:["Salesforce SCV","Amazon Connect","Amazon Lex","REST APIs"],challenge:"Agents needed customer context during calls and a simpler way to record interactions and manage follow-up.",solution:"We integrated Salesforce Service Cloud Voice with screen-pop, automatic interaction logging, and case creation. Lex-based self-service supported routine customer requests.",delivery:["CRM screen-pop and interaction logging","Case creation and follow-up automation","Conversational self-service integration"],result:"Approximately 35% higher agent productivity and 40% less manual follow-up."},
 {id:"migration",sector:"Telecom",title:"Cloud contact center migration",summary:"Moving production journeys to a new platform while preserving essential integrations.",metric:"8+",metricLabel:"contact flows rebuilt",stack:["Genesys Cloud CX","Amazon Connect","Terraform","Jenkins"],challenge:"The client needed to migrate legacy contact flows, routing, and connected workflows to a cloud platform with a more flexible change process.",solution:"We mapped Genesys journeys and rebuilt them in Amazon Connect. CRM integration, infrastructure as code, and CI/CD supported delivery, with Cyara validation before launch.",delivery:["Contact flow mapping and routing redesign","CRM integration and automated deployment","Journey validation and cutover preparation"],result:"Eight or more contact flows were migrated. A vendor change cycle that took weeks was reduced to hours."},
 {id:"self-service",sector:"Telecom",title:"Conversational self-service",summary:"Resolving recurring requests through voice automation with deliberate fallback paths.",metric:"18–22%",metricLabel:"call deflection on targeted intents",stack:["Amazon Lex","AWS Lambda","Amazon Connect","Cyara"],challenge:"Routine enquiries were reaching agents even when customers could complete the request through a focused self-service journey.",solution:"We built Lex-powered IVR with Lambda fulfillment and defined fallback behavior. Cyara test coverage included successful journeys, negative cases, timeouts, and errors.",delivery:["Intent design and backend fulfillment","Fallback and agent escalation logic","Positive, negative, and timeout testing"],result:"18–22% call deflection on the targeted self-service intents."},
 {id:"operations",sector:"Financial services",title:"Coordinated contact center operations",summary:"Connecting calling platforms, routing, and customer workflows for collections operations.",metric:"35%",metricLabel:"improvement in SLA compliance",stack:["Genesys Cloud CX","Avaya","Salesforce","ServiceNow"],challenge:"The client needed coordinated inbound and outbound operations across multiple contact center platforms and customer systems.",solution:"We supported dialer operations, IVR and ACD workflows, and integrations with CRM and service management tools to improve operational coordination.",delivery:["Outbound calling and routing operations","CRM and service management integration","Contact center performance visibility"],result:"Approximately 35% better SLA compliance across the supported operations."},
 {id:"policy-support",sector:"Insurance",title:"Simpler policyholder support",summary:"Making routine policy and premium enquiries easier to resolve.",metric:"18%",metricLabel:"fewer routine agent enquiries",stack:["Avaya","Genesys Cloud CX","NICE","ServiceNow"],challenge:"Policyholders needed straightforward support for policy issuance, renewals, and premium enquiries across inbound and outbound channels.",solution:"We connected IVR and ACD support with recording, CRM screen-pop, and service ticketing. Self-service journeys helped customers handle routine enquiries.",delivery:["Policy and premium enquiry journeys","Recording, CRM, and ticketing connections","Self-service for routine support needs"],result:"Approximately 18% fewer routine agent-handled enquiries through IVR self-service."}
];

export const deliverySteps = [
 {title:"Discover",copy:"Understand your customers, current systems, and the operational problem to solve.",items:["Stakeholder conversations","Journey and architecture review","Priorities and constraints"]},
 {title:"Design",copy:"Agree how the solution will work, how it will connect, and how success will be tested.",items:["Solution architecture","Scope and delivery sequence","Validation plan"]},
 {title:"Deliver",copy:"Build the journeys and integrations, validate the paths, and prepare your team for launch.",items:["Implementation and integration","Journey and failure-path testing","Launch and handover"]},
 {title:"Improve",copy:"Use operational feedback and visibility to find friction and plan the next improvements.",items:["Monitoring and issue review","Workflow refinement","Prioritized improvements"]}
];
